sudo: false
language: python
python:
  - "3.5.2"
branches:
  only:
    - master


cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
# command to install dependencies
install:
  - pip install -r requirements.txt
  - cd app && npm install && bower install 
# command to run tests
script: ./configure && make build/rc.model && cd app/BayesCMD/testing && nosetests --nocapture --with-coverage
